services:
  frontend-private:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fp-cursala
    restart: unless-stopped
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=development
    networks:
      - cursala-net

networks:
  cursala-net:
    driver: bridge
